repositories {
    mavenLocal()
    exclusiveContent {
        forRepository { maven { url = 'https://maven.caffeinemc.net/releases' } }
        filter { includeGroup('net.caffeinemc') }
    }
    exclusiveContent {
        forRepository { maven { url = 'https://maven.sinytra.org/' } }
        filter { includeGroupAndSubgroups('org.sinytra') }
    }
    exclusiveContent {
        forRepository { maven { url = 'https://maven.fabricmc.net/' } }
        filter { includeGroup('net.fabricmc') }
    }
    mavenCentral()
    maven { url = 'https://maven.neoforged.net/releases' }

    maven {
        name = 'GTCEu Maven'
        url = 'https://maven.gtceu.com'
        content {
            includeGroup 'com.gregtechceu.gtceu'
            includeGroup 'brachy.modularui'
        }
    }
    maven {
        name = 'ModMaven'
        url = 'https://modmaven.dev/'
        content {
            includeGroup 'org.appliedenergistics'
            includeGroup 'de.mari_023'
            includeGroup 'mezz.jei'
        }
    }
    maven {
        name = 'FirstDarkDev'
        url = 'https://maven.firstdark.dev/snapshots'
    }
    maven {
        name = 'BlameJared'
        url = 'https://maven.blamejared.com/'
    }
    exclusiveContent {
        forRepository { maven { name = 'TomaConfiguration'; url = 'https://repo.repsy.io/mvn/toma/public' } }
        filter { includeGroup('dev.toma.configuration') }
    }
    exclusiveContent {
        forRepository { maven { name = 'Shedaniel'; url = 'https://maven.shedaniel.me/' } }
        filter {
            includeGroupAndSubgroups('me.shedaniel')
            includeGroup('dev.architectury')
        }
    }
    exclusiveContent {
        forRepository { maven { name = 'Devos'; url = 'https://mvn.devos.one/snapshots/' } }
        filter { includeGroup('com.tterrag.registrate') }
    }
    exclusiveContent {
        forRepository { maven { name = 'TerraformersMC'; url = 'https://maven.terraformersmc.com/releases/' } }
        filter { includeGroup('dev.emi') }
    }
    exclusiveContent {
        forRepository { maven { name = 'Modrinth'; url = 'https://api.modrinth.com/maven/' } }
        filter { includeGroup('maven.modrinth') }
    }
    exclusiveContent {
        forRepository { maven { name = 'CurseMaven'; url = 'https://cursemaven.com/' } }
        filter { includeGroup('curse.maven') }
    }
}
