org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.java.installations.auto-download=false

mod_id = nebulaeae2
mod_name = Nebulae AE2
mod_version = 0.1.0
mod_description = Frontiers AE2 integration layer, rebuilt on modern AE2.
mod_authors = Ghostipedia
mod_license = LGPL-3.0
mod_url = https://github.com/Ghostipedia/NebulaeAE2/
mod_issue_tracker = https://github.com/Ghostipedia/NebulaeAE2/issues/
maven_group = com.ghostipedia.nebulaeae2
